### ISSUE TITLE
onnx.optimizer does not exist anymore

### ISSUE THREAD

**Issue by londumas** [gmalivenko/pytorch2keras#132]
https://github.com/gmalivenko/pytorch2keras/blob/59bdb46ca55e951f527c9b729ee8602dcfdb28b6/pytorch2keras/converter.py#L8

The code tries to import a library, `onnx.optimizer`, which no longer exists in latests onnx.
The imports work for onnx <1.9.0, does not work for >= 1.9.0.
A simple solution for now is to comment out the import

**Comment by jcwchen** [comment]
FYI: Actually onnxoptimizer is still available and ongoing from another repo: https://github.com/onnx/optimizer. It was moved out from ONNX package since ONNX 1.9.0. IIUC, you can still use it with the latest ONNX. Thanks!
